// <auto-generated />
namespace VidRental.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class rerunAddMembershipType : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(rerunAddMembershipType));
        
        string IMigrationMetadata.Id
        {
            get { return "201901230240558_re-runAddMembershipType"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
